"""empty message

Revision ID: 3c36303523fe
Revises: a7a1f5cbc2c1
Create Date: 2022-12-14 18:36:33.165158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c36303523fe'
down_revision = 'a7a1f5cbc2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('address2',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('userName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userName', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
        batch_op.alter_column('address2',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('dob',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
