"""empty message

Revision ID: a7a1f5cbc2c1
Revises: 7b341695f43f
Create Date: 2022-12-13 00:53:15.728955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a1f5cbc2c1'
down_revision = '7b341695f43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('address2', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('city', sa.String(length=25), nullable=False))
    op.add_column('user', sa.Column('country', sa.String(length=25), nullable=False))
    op.add_column('user', sa.Column('dob', sa.String(length=10), nullable=False))
    op.add_column('user', sa.Column('firstName', sa.String(length=25), nullable=False))
    op.add_column('user', sa.Column('lastName', sa.String(length=25), nullable=False))
    op.add_column('user', sa.Column('state', sa.String(length=25), nullable=False))
    op.add_column('user', sa.Column('userName', sa.String(length=25), nullable=False))
    op.add_column('user', sa.Column('zipcode', sa.String(length=100), nullable=False))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('user', 'password',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.drop_column('user', 'zipcode')
    op.drop_column('user', 'userName')
    op.drop_column('user', 'state')
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'firstName')
    op.drop_column('user', 'dob')
    op.drop_column('user', 'country')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address2')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
